---
abstract: 'Send SMS using your 160By2 account!'
author:
  - 'Mohan Prasad Gutta <mohanprasadgutta@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SMS-160By2
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Data::Dumper: 0
  HTML::Form: 0
  POSIX: 0
  Test::More: 0
  WWW::Mechanize: 0
version: 0.04
